# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b38552383c9e1ef086c6caa189719e4f0b437a6d66153563bf0c396b5517524614db7b841e2b47596106f38092b9594b8effe769b46b5da9a8205b2e08acf4b3

test:
  secret_key_base: 96936f9d2d241552af2b10188ca13f00e021a9579728a5abcc92c6f27732b27a043c8fe7577679375fa2a5c3e0dbebcfa5ce5f37b97dca15fc8134fd3e2e422d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
